SEARCH_DIR("/lib64/")
SEARCH_DIR("/lib/")
SEARCH_DIR("/usr/lib64/")
SEARCH_DIR("/usr/lib/")
SEARCH_DIR("/usr/lib/gcc/x86_64-pc-linux-gnu/12.1.0/")
SEARCH_DIR("./resources/Buttons/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/gtk2/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/lazarus/components/freetype/lib/x86_64-linux/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/ccr/synapse/lib/x86_64-linux/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/lazarus/components/lazutils/lib/x86_64-linux/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/lazarus/packager/units/x86_64-linux/")
SEARCH_DIR("./")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/httpd22/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/rtl/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/tplylib/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/googleapi/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/opengles/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pthreads/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/gnutls/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-stl/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/bzip2/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-pdf/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/gnome1/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-db/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/opencl/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/imlib/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-js/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/uuid/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fppkg/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/mysql/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/libsee/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/lua/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-fpcunit/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/libgd/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/dblib/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/ncurses/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fpmkunit/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/gtk2/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/graph/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-image/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/numlib/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/libpng/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-json/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/zorba/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/ggi/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-net/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/vcl-compat/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/paszlib/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-sound/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/libvlc/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/ibase/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/modplug/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-sdo/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/ldap/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/x11/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-registry/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/aspell/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/libmicrohttpd/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/rtl-generics/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/syslog/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-res/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/proj4/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/unzip/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/xforms/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/newt/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/opengl/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/gmp/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/jni/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/libusb/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/libfontconfig/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/gdbint/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/openssl/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fv/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/libenet/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/webidl/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/tcl/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/httpd24/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/sdl/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pcap/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-web/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/regexpr/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/a52/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-xml/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-report/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/gdbm/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fftw/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/sqlite/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/rsvg/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/hash/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/oggvorbis/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/dts/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/bfd/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/libcurl/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/postgres/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/rtl-objpas/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/chm/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/hermes/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/rtl-unicode/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/imagemagick/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/zlib/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/oracle/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/cdrom/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/libmagic/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/rtl-extra/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/utils-pas2js/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/ptc/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/svgalib/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fpgtk/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/utmp/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-extra/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/symbolic/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/rtl-console/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/odbc/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-passrc/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/mad/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/libffi/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/users/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fpindexer/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/libxml2/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/cairo/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/libcups/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/openal/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pastojs/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pxlib/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-process/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/iconvenc/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/dbus/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-base/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/libgc/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-async/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fastcgi/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/gtk1/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/libtar/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/odata/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/")
SEARCH_DIR("/home/toadwick/Apps/Lazarus-Stable/fpc/bin/x86_64-linux/")
INPUT(
/lib64/crti.o
/usr/lib/gcc/x86_64-pc-linux-gnu/12.1.0/crtbeginS.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/rtl/si_c.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/rtl/abitag.o
/home/toadwick/Apps/Lazarus-Stable/projects/AmazingCloaker/lib/x86_64-linux/AmazingCloaker.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/rtl/system.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/rtl/lnfodwrf.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/rtl/exeinfo.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/rtl/strings.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/rtl/fpintres.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/rtl/objpas.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/rtl/cthreads.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/gtk2/interfaces.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/forms.o
/home/toadwick/Apps/Lazarus-Stable/projects/AmazingCloaker/lib/x86_64-linux/unit1.o
/home/toadwick/Apps/Lazarus-Stable/projects/AmazingCloaker/lib/x86_64-linux/about.o
/home/toadwick/Apps/Lazarus-Stable/projects/AmazingCloaker/lib/x86_64-linux/prefs.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/rtl/linux.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/rtl/baseunix.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/rtl/unix.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/rtl/unixtype.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/rtl/initc.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/rtl/dl.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/rtl/unixutil.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/rtl/ctypes.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/rtl/cwstring.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/rtl/dynlibs.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/rtl/unixcp.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/gtk2/gtk2disableliboverlay.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/gtk2/gtk2int.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/rtl/classes.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/rtl/sysutils.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/rtl/types.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/rtl/typinfo.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/rtl/rtlconsts.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/rtl/errors.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/rtl/sysconst.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/rtl/math.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/x11/xlib.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/x11/x.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/gtk2/gdk2x.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/gtk2/gdk2pixbuf.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/gtk2/gtk2.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/gtk2/gdk2.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/gtk2/glib2.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/gtk2/pango.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/lmessages.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/lclproc.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/lclintf.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/lcltype.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/dialogs.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/controls.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/lclstrconsts.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/graphics.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/menus.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/themes.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/buttons.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/stdctrls.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/checklst.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/comctrls.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/extctrls.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/lclplatformdef.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/interfacebase.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/wslclclasses.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/wscontrols.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/gtk2/gtk2winapiwindow.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/gtk2/gtk2globals.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/gtk2/gtk2proc.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/gtk2/gtk2def.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/gtk2/gtk2fontcache.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/gtk2/gtk2extra.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/gtk2/gtk2msgqueue.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/components/lazutils/lib/x86_64-linux/graphtype.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/components/lazutils/lib/x86_64-linux/graphmath.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/components/lazutils/lib/x86_64-linux/lazfileutils.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/components/lazutils/lib/x86_64-linux/lazutf8.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/components/lazutils/lib/x86_64-linux/dynhasharray.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/components/lazutils/lib/x86_64-linux/maps.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/components/lazutils/lib/x86_64-linux/integerlist.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/components/lazutils/lib/x86_64-linux/lazloggerbase.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/components/lazutils/lib/x86_64-linux/laztracer.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/components/lazutils/lib/x86_64-linux/lazutilities.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/components/lazutils/lib/x86_64-linux/lazstringutils.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/x11/xrender.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/cairo/cairo.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/gtk2/atk.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/components/lazutils/lib/x86_64-linux/fpcadds.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/components/lazutils/lib/x86_64-linux/lazclasses.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/components/lazutils/lib/x86_64-linux/lazmethodlist.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/rtl-objpas/strutils.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-base/gettext.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/components/lazutils/lib/x86_64-linux/laz_avl_tree.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/components/lazutils/lib/x86_64-linux/lazutilsstrconsts.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/components/lazutils/lib/x86_64-linux/fileutil.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/components/lazutils/lib/x86_64-linux/utf8process.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/components/lazutils/lib/x86_64-linux/lazsysutils.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-image/fpimage.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/intfgraphics.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-image/fpreadbmp.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-image/fpwritebmp.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-image/bmpcomn.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-image/fpreadpng.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-image/fpwritepng.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-image/fpreadtiff.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-image/fpwritetiff.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-image/fptiffcmn.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/lclversion.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/icnstypes.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-image/fpimgcmn.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-image/pngcomn.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/paszlib/zstream.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/paszlib/zbase.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/paszlib/gzio.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/hash/crc.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/paszlib/zdeflate.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/paszlib/zinflate.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/paszlib/trees.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/paszlib/adler.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/paszlib/infblock.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/paszlib/infutil.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/paszlib/infcodes.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/paszlib/inftrees.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/paszlib/inffast.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/components/lazutils/lib/x86_64-linux/lazversion.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-base/contnrs.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-image/fpcanvas.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-image/fpreadpnm.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-image/fpwritepnm.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-image/fpreadjpeg.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-image/fpwritejpeg.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-image/fpreadgif.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/lresources.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/lclrescache.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/wsreferences.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-image/clipping.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jpeglib.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jdapimin.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jdatasrc.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jdapistd.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jmorecfg.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jdeferr.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jinclude.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jerror.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jmemmgr.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jdmarker.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jdinput.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jcomapi.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jutils.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jmemnobs.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jdmaster.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jdcolor.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jdsample.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jdpostct.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jddctmgr.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jdphuff.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jdhuff.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jdcoefct.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jdmainct.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jquant1.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jquant2.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jdmerge.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jdct.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jidctfst.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jidctint.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jidctflt.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jidctred.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jcapistd.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jcapimin.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jdatadst.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jcparam.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jcinit.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jcmarker.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jcphuff.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jchuff.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jcmaster.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jccolor.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jcsample.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jcprepct.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jcdctmgr.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jccoefct.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jcmainct.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jfdctint.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jfdctfst.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/pasjpeg/jfdctflt.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/rtl-objpas/variants.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/components/lazutils/lib/x86_64-linux/lazconfigstorage.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/components/lazutils/lib/x86_64-linux/dynqueue.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/rtl-objpas/varutils.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/components/lazutils/lib/x86_64-linux/avglvltree.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/components/lazutils/lib/x86_64-linux/lazdbglog.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-base/syncobjs.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/tmschema.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/rtl/fgl.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/components/lazutils/lib/x86_64-linux/masks.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-process/process.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-process/pipes.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/rtl/termio.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/buttonpanel.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/lclclasses.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/clipbrd.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/lcltaskdialog.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/components/lazutils/lib/x86_64-linux/uitypes.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-base/custapp.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/customtimer.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/actnlist.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/helpintfs.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/imglist.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-base/singleinstance.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-image/fpimgcanv.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-image/fppixlcanv.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-image/pixtools.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-image/ellipses.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/wsimglist.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/wsproc.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/wsfactory.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/propertystorage.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-base/rttiutils.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/wsmenus.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/components/lazutils/lib/x86_64-linux/lazlogger.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/chm/fasthtmlparser.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/rtl-objpas/system.uitypes.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/wsforms.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/imagelistcache.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/components/lazutils/lib/x86_64-linux/textstrings.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/components/lazutils/lib/x86_64-linux/extendedstrings.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/wsstdctrls.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/wsbuttons.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/popupnotifier.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/wsextctrls.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/wsdialogs.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/wschecklst.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/toolwin.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/wscomctrls.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/wstoolwin.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/gtk2/gtk2ext.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/extdlgs.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/lclmessageglue.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/gtk2/gtk2debug.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/calendar.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/calcform.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/wscalendar.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/wsextdlgs.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/messages.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/lclmemmanager.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/gtk2/gtk2wsprivate.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-base/uriparser.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/gtk2/gtk2wscontrols.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/components/lazutils/lib/x86_64-linux/lazlinkedlist.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/gtk2/gtk2wsfactory.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/gtk2/gtk2wsstdctrls.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/gtk2/gtk2wschecklst.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/gtk2/gtk2themes.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/spin.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/grids.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/pairsplitter.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/wsspin.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-xml/htmldefs.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/maskedit.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/components/lazutils/lib/x86_64-linux/dynamicarray.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/components/lazutils/lib/x86_64-linux/laz2_xmlcfg.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/components/lazutils/lib/x86_64-linux/lcsvutils.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/components/lazutils/lib/x86_64-linux/lazfilecache.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/components/lazutils/lib/x86_64-linux/laz2_dom.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/components/lazutils/lib/x86_64-linux/laz2_xmlread.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/components/lazutils/lib/x86_64-linux/laz2_xmlwrite.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/components/lazutils/lib/x86_64-linux/laz2_xmlutils.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/wsgrids.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/wspairsplitter.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/gtk2/gtk2wsbuttons.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/gtk2/gtk2wscalendar.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/gtk2/gtk2wscomctrls.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/gtk2/gtk2wsdialogs.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/gtk2/gtk2wsextctrls.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/gtk2/gtk2wsextdlgs.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/gtk2/gtk2wsforms.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/gtk2/gtk2wsgrids.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/gtk2/gtk2wsimglist.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/gtk2/gtk2wsmenus.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/gtk2/gtk2wsspin.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/gtk2/gtk2wspairsplitter.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/gtk2/unitywsctrls.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/gtk2/gtk2cellrenderer.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/gtk2/gtk2listviewtreemodel.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-db/sqlite3conn.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-db/sqldb.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-db/db.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/lazhelphtml.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/dbgrids.o
/home/toadwick/Apps/Lazarus-Stable/ccr/synapse/lib/x86_64-linux/ftpsend.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/sqlite/sqlite3dyn.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-db/bufdataset.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/rtl-objpas/fmtbcd.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-base/maskutils.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-db/dbconst.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-db/bufdataset_parser.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-db/dbf_prscore.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-db/dbf_prsdef.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-db/dbf_prssupp.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-db/sqlscript.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-db/sqltypes.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/rtl-objpas/dateutils.o
/home/toadwick/Apps/Lazarus-Stable/lazarus/lcl/units/x86_64-linux/lazhelpintf.o
/home/toadwick/Apps/Lazarus-Stable/ccr/synapse/lib/x86_64-linux/blcksock.o
/home/toadwick/Apps/Lazarus-Stable/ccr/synapse/lib/x86_64-linux/synautil.o
/home/toadwick/Apps/Lazarus-Stable/ccr/synapse/lib/x86_64-linux/synaip.o
/home/toadwick/Apps/Lazarus-Stable/ccr/synapse/lib/x86_64-linux/synsock.o
/home/toadwick/Apps/Lazarus-Stable/ccr/synapse/lib/x86_64-linux/synafpc.o
/home/toadwick/Apps/Lazarus-Stable/ccr/synapse/lib/x86_64-linux/synacode.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/rtl-extra/sockets.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-net/netdb.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-extra/fileinfo.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-res/winpeimagereader.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-res/elfreader.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-res/machoreader.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-res/resource.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-res/versiontypes.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-res/versionresource.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-res/resdatastream.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-res/resourcetree.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-res/resmerger.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-res/resfactory.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-res/stringtableresource.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-res/groupiconresource.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-res/groupcursorresource.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-res/groupresource.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-res/icocurtypes.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-res/coffreader.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-res/cofftypes.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-res/elfconsts.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-res/elftypes.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-res/strtable.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-res/fpcrestypes.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-res/machotypes.o
/home/toadwick/Apps/Lazarus-Stable/fpc/units/x86_64-linux/fcl-res/machoconsts.o
)
INPUT(
-lpthread
-ldl
-lgdk-x11-2.0
-lgtk-x11-2.0
-lX11
-lgdk_pixbuf-2.0
-lgobject-2.0
-lglib-2.0
-lgthread-2.0
-lgmodule-2.0
-lpango-1.0
-lcairo
-latk-1.0
)
GROUP(
-lc
)
INPUT(
/usr/lib/gcc/x86_64-pc-linux-gnu/12.1.0/crtendS.o
/lib64/crtn.o
)
SECTIONS
{
  .fpcdata           :
  {
    KEEP (*(.fpc .fpc.n_version .fpc.n_links))
  }
  .threadvar : { *(.threadvar .threadvar.* .gnu.linkonce.tv.*) }
}
INSERT AFTER .data;
